name: CI for the Advent of Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn ci:format
      - run: yarn ci:lint
      - run: yarn test
